---
- name: list installed modules
  shell: 'ls {{ nginx_mods_path }} | sed "s/\.so$//"'
  check_mode: False
  changed_when: False
  register: lsmods
  tags: nginx, config

- name: nginx modules to load
  template:
    dest: '{{ nginx_etcdir }}/modules.d/load_{{ module }}.conf'
    src: module.conf.j2
    mode: '0640'
    group: '{{ www_group }}'
  with_items: '{{ nginx_modules }}'
  loop_control:
    loop_var: module
  when: 'module in lsmods.stdout_lines'
  notify: restart nginx
  tags: nginx, config


